### ISSUE TITLE
Unintentional Nuking of Instruction Keyframe for All Blockbench Formats

### ISSUE THREAD

**Issue by SteelChikorita** [LoneDev6/itemsadder-entity#17]
Whilst using the newest version of the Entity Plugin, I have noticed that there has been a nuking of the Instruction Keyframes within the Effects timeline in the Animation section. This removal extends past the itemsadder format to the entirety of Blockbench and effects all formats, which is a detriment if other models utilize instruction keyframes for certain actions.

Steps to Reproduce:
1. Have Blockbench and the latest version of the Itemsadder entity format installed. 
2. Open a Generic format model.
3. Go to Animate.
4. Click the "Animate Effects" wand near the timeline and place an Instructions Keyframe.
5. Notice that under Keyframe (Instructions) there is nowhere to input text when there should be an input box.

Expected Outcome: The Instruction Keyframes should not be nuked for non-Itemsadder entity format projects.

**Comment by LoneDev6** [comment]
> Whilst using the newest version of the Entity Plugin

Are you sure this doesn't happen on previous versions? for example 1.2.0 and 1.1.2.

Thanks let me know

**Comment by LoneDev6** [comment]
Anyway here is an updated version.
Let me know if everything works as expected.
[iaentitymodel_test_1.2.2.zip](https://github.com/LoneDev6/itemsadder-entity/files/11892326/iaentitymodel_test_1.2.2.zip)

**Comment by SteelChikorita** [comment]
> Anyway here is an updated version. Let me know if everything works as expected. [iaentitymodel_test_1.2.2.zip](https://github.com/LoneDev6/itemsadder-entity/files/11892326/iaentitymodel_test_1.2.2.zip)

Tried this out and the issue seems to be fixed for generic format! The input box for the instruction script now shows up as intended. :)

**Comment by LoneDev6** [comment]
Amazing!
Thanks for the test
