### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by swissme** [LoneDev6/itemsadder-entity#20]
```
------ Error ------
Cannot read properties of undefined (reading 'export')  //  "Time to fire up the ol' debugger!"
------ Stack ------
TypeError: Cannot read properties of undefined (reading 'export')
    at computeBones (<anonymous>:11751:24)
    at computeAnimationData (<anonymous>:23322:19)
```

This error was shown when trying to export a converted bbmodel to itemsadder entity.

**Comment by LoneDev6** [comment]
Is it possible for you to share your model file on the forum?
You can open a "duplication issue" thread even if it's not related to duplication issues, but this will create a private thread only me can read where you can post the model file privately.
https://forum.devs.beer/

![image](https://github.com/LoneDev6/itemsadder-entity/assets/27242001/dfacc2b2-42b2-4b4c-8dfe-2af0c673c5cd)

Or you can post it if you don't care about privacy of the file, you decide.

**Comment by Tink-Bell** [comment]
![image](https://github.com/user-attachments/assets/25ba8e49-4a6c-40b7-b8a2-b61029755501)
