### ISSUE TITLE
The java model rotation value is incorrect 

### ISSUE THREAD

**Issue by yungui520** [LoneDev6/itemsadder-entity#24]
Hello, I have some problems when exporting the project, it means that the java model has the wrong rotation value, I want to know how to export this file, thank you very much for the answer
![Desktop Screenshot 2024 03 05 - 20 24 27 17](https://github.com/LoneDev6/itemsadder-entity/assets/162322584/f7eaaa2a-3e8d-4eab-a047-67afbde7cf76)

**Comment by LoneDev6** [comment]
You have a "cube" (not bone) which has a rotation which is not accepted by Minecraft.
Bones have no rotation limits, but cubes do have the vanilla Minecraft models rotation limits.
If I recall the limit is that you can rotate cubes only by increments of `22.5` degrees.

So check all your cubes and identify the bad ones.
Strange that the extension didn't automatically do that, if I recall I coded a method to do that on import/conversion.

**Comment by yungui520** [comment]
> 你有一个“立方体”（不是骨头），它的旋转不被 Minecraft 接受。骨头没有旋转限制，但立方体确实有原版的 Minecraft 模型旋转限制。如果我还记得的话，限制是你只能以度为单位旋转立方体。`22.5`
> 
> 因此，请检查所有立方体并找出坏的立方体。奇怪的是，扩展程序并没有自动执行此操作，如果我记得我编写了一个在导入/转换时执行此操作的方法。

Thank you, my friend, your reply has helped us a lot in our work and we are very grateful to you.

**Comment by LoneDev6** [comment]
No problem! I hope you will leave a good review, it will help me so much
