### ISSUE TITLE
Export problems

### ISSUE THREAD

**Issue by skellf** [LoneDev6/itemsadder-entity#26]
Hello, i've made a model and tried to export it into itemsadder entity but i have an error saying that i have some cubes with invalid rotation. I've checked all of my cubes and i guess that all of them were fine to Minecraft. What's the issue?
![image](https://github.com/LoneDev6/itemsadder-entity/assets/131668297/8a9d389f-16ac-42d7-bf24-48d9120abe50)

Here's the model: [trader.zip](https://github.com/user-attachments/files/15820582/trader.zip)

**Comment by LoneDev6** [comment]
CUBE rotations must be supported by the java format: `45, 22.5, 0, -22.5, -45`.
Bones (groups, folders) rotations have no limit.

**Comment by skellf** [comment]
Thanks, it worked!

**Comment by Nightkau** [comment]
Sorry to necro this but i get this error even when i have gone through and checked the rotations on every cube... really not sure what else i can check but they're all definitely either 45, 22.5, 0, -22.5, or -45. I've been able to export some models fine, but not others.

**Comment by LoneDev6** [comment]
@Nightkau try to attach the itemsadder entity project model here.
feel free to remove all bones and data that is not needed so that i can easily reproduce the issue without exposing your full project publicly.
