### ISSUE TITLE
Blockbensh entity plugin not working 

### ISSUE THREAD

**Issue by MagmaFaridneaYT** [LoneDev6/itemsadder-entity#28]
The plugin for creating itemadder entities on blockbensh no longer works, it no longer appears

**Comment by LoneDev6** [comment]
![image](https://github.com/user-attachments/assets/b42053c8-89c6-4f10-b154-72e33340344f)
![image](https://github.com/user-attachments/assets/36c4da0e-5d12-4a0a-9821-db7505d82534)
