### ISSUE TITLE
No working Scale Animations

### ISSUE THREAD

**Issue by Der-Vlapos** [LoneDev6/itemsadder-entity#5]
**Describe the bug**
Trying to do any scala animations, where keyframes have the values >1, get export error

**To Reproduce**
1. create animations
2. add scale keyframes with values >1
3. Try to make export

**Expected behavior**
Normal export

**Error Message**
```
The bone '*bone-name*' has an invalid scaling during one of your animations: '*bone-name*': [scale value x, scale value y, scale value z] > maximum: [3.125, 3.125, 3.125]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/103891631/182913646-89df5d77-0dd7-4c8c-9b2d-4fae4f6abe8f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11/10

**Additional context**
the value > maximum: [3.125, 3.125, 3.125] is constant in each situation

**Comment by LoneDev6** [comment]
It surely is because the model is too big, you might need to toggle this

![image](https://user-images.githubusercontent.com/27242001/183048692-245b0792-f21d-4fb3-a44c-e5a672ff9190.png)
