### ISSUE TITLE
no such file or directory, 

### ISSUE THREAD

**Issue by jugandomiguel** [LoneDev6/itemsadder-entity#7]
**Describe the bug**

**To Reproduce**
1. Go to plugin tab
2. Click on export
3. See error

**Expected behavior**

**Error Message**
------ Error ------
ENOENT: no such file or directory, open 'C:\Users\USUARIO\Desktop\assets\pets\textures\entity\pet_bunny\pet_bunny.png'  //  "Time to fire up the ol' debugger!"
------ Stack ------
Error: ENOENT: no such file or directory, open 'C:\Users\USUARIO\Desktop\assets\pets\textures\entity\pet_bunny\pet_bunny.png'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1810)
    at U (<anonymous>:223:7467)
    at <anonymous>:234:43160
    at Array.forEach (<anonymous>)
    at Mu (<anonymous>:234:43053)
    at n (<anonymous>:234:43912)
    at <anonymous>:234:44245
    at Array.forEach (<anonymous>)
    at n (<anonymous>:234:44233)

Build ID: local-5dda05a7893c18ead86fc57ae55ba033defc5292a2fc7f69250ca6dfe353f7a2
Paste the message the error displayed when it occurred (if applicable)
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Version [e.g. v0.2.0]

**Additional context**
Add any other context about the problem here.

**Comment by jugandomiguel** [comment]
![image](https://user-images.githubusercontent.com/73621705/201635111-9d5fbe5f-33a7-4f68-8c32-6ad4e624c915.png)

**Comment by jugandomiguel** [comment]
also put the same thing in namescape and in the entity id
![image](https://user-images.githubusercontent.com/73621705/201635435-aa9a5895-d62a-478f-a570-5e7b611101db.png)

**Comment by LoneDev6** [comment]
>  no such file or directory, open 'C:\Users\USUARIO\Desktop\assets\pets\textures\entity\pet_bunny\pet_bunny.png'

make sure your files exist.

Also why are you calling your entity "pets"?
Shouldn't it be pet_bunny?
